apiVersion: v1
kind: Namespace
metadata:
  name: gracefulset-test
---
apiVersion: apps.gracefulset.io/v1alpha1
kind: GracefulSet
metadata:
  name: my-app
  namespace: gracefulset-test
spec:
  replicas: 3
  version: "2024.1.0"
  drainPolicy:
    mode: WaitForCompletion
    maxDrainingPods: 10
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        gracefulset.io/name: my-app
    spec:
      containers:
        - name: app
          image: public.ecr.aws/docker/library/nginx:alpine
          ports:
            - containerPort: 80
              name: http
          env:
            - name: APP_VERSION
              value: "2024.1.0"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
