//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainPolicy) DeepCopyInto(out *DrainPolicy) {
	*out = *in
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DrainCheck != nil {
		in, out := &in.DrainCheck, &out.DrainCheck
		*out = new(DrainCheck)
		**out = **in
	}
	if in.MaxDrainingPods != nil {
		in, out := &in.MaxDrainingPods, &out.MaxDrainingPods
		*out = new(int32)
		**out = **in
	}
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainCheck) DeepCopyInto(out *DrainCheck) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new DrainCheck.
func (in *DrainCheck) DeepCopy() *DrainCheck {
	if in == nil {
		return nil
	}
	out := new(DrainCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new DrainPolicy.
func (in *DrainPolicy) DeepCopy() *DrainPolicy {
	if in == nil {
		return nil
	}
	out := new(DrainPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GracefulSet) DeepCopyInto(out *GracefulSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new GracefulSet.
func (in *GracefulSet) DeepCopy() *GracefulSet {
	if in == nil {
		return nil
	}
	out := new(GracefulSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GracefulSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GracefulSetList) DeepCopyInto(out *GracefulSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GracefulSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new GracefulSetList.
func (in *GracefulSetList) DeepCopy() *GracefulSetList {
	if in == nil {
		return nil
	}
	out := new(GracefulSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GracefulSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GracefulSetSpec) DeepCopyInto(out *GracefulSetSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.DrainPolicy.DeepCopyInto(&out.DrainPolicy)
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new GracefulSetSpec.
func (in *GracefulSetSpec) DeepCopy() *GracefulSetSpec {
	if in == nil {
		return nil
	}
	out := new(GracefulSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GracefulSetStatus) DeepCopyInto(out *GracefulSetStatus) {
	*out = *in
	if in.DrainingVersions != nil {
		in, out := &in.DrainingVersions, &out.DrainingVersions
		*out = make([]VersionStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new GracefulSetStatus.
func (in *GracefulSetStatus) DeepCopy() *GracefulSetStatus {
	if in == nil {
		return nil
	}
	out := new(GracefulSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionStatus) DeepCopyInto(out *VersionStatus) {
	*out = *in
	if in.OldestPodCreation != nil {
		in, out := &in.OldestPodCreation, &out.OldestPodCreation
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new VersionStatus.
func (in *VersionStatus) DeepCopy() *VersionStatus {
	if in == nil {
		return nil
	}
	out := new(VersionStatus)
	in.DeepCopyInto(out)
	return out
}
